# Generated by Django 4.1 on 2023-07-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['created_at'], 'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
    ]
