# Generated by Django 4.1 on 2023-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_avaliation',
            field=models.CharField(choices=[('regular', 'Regular'), ('bom', 'Bom'), ('ótimo', 'Otimo'), ('excelente', 'Excelente')], default='regular', max_length=9),
        ),
    ]
