# Generated by Django 4.1 on 2023-07-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_result_candidate_selective_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='selective_process',
            field=models.CharField(max_length=255),
        ),
    ]
