# Generated by Django 4.1 on 2023-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_selective_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='note',
            field=models.TextField(default='Sem observações'),
        ),
    ]
