# Generated by Django 4.1 on 2023-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='note',
            field=models.TextField(),
        ),
    ]
